apiVersion: apps/v1
kind: Deployment
metadata:
  name: mantenimiento
spec:
  replicas: 3
  selector:
    matchLabels:
      role: mantenimiento
  template:
    metadata:
      labels:
        role: mantenimiento
    spec:
      containers:
      - name: mantenimiento
        image: harbor.osde.ar/os-turnos/mantenimiento-16:7086cbc4
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mantenimiento
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    role: mantenimiento