apiVersion: apps/v1
kind: Deployment
metadata:
  name: mantenimiento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mantenimiento
  template:
    metadata:
      labels:
        app: mantenimiento
    spec:
      containers:
      - name: mantenimiento
        image: edumarvega/react-app
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mantenimiento
spec:
  type: NodePort
  selector:
    app: mantenimiento
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31000